name: papyr
description: Cross-platform document scanner library for Flutter/Dart
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  ffi: ^2.1.3
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
